### ISSUE TITLE
Question: about the parenthesized training set

### ISSUE THREAD

**Issue by antgr** [aghie/tree2labels#2]
Hi, is the parenthesized training set that you used, provided as a reference example, in order to run the code and reproduce your results?

**Comment by aghie** [comment]
Those datasets you are referring to (I think) are the English Penn Treebank (PTB) and the Chinese Penn Treebank (CTB). Sadly, I am not allowed to redistribute them as a part of this repository because they are protected under copyright (e.g. https://catalog.ldc.upenn.edu/LDC2013T21). The example just tries to illustrate how the encoding works. 

If you already have a license for any of these datasets, then you just need to run dataset.py (for the official splits for parsing) to transform the treebank and then train your own models. If you have a license *and* you are also interested in using the same set of predicted PoS tags that I used in the paper, send me an e-mail and I will send them to you.

**Comment by antgr** [comment]
Thank you for the clarification! 
<<The example just tries to illustrate how the encoding works.>>  I don't understand what do you mean "example". Do you have a sample (toy) dataset for running the code in that? I think that this would be really helpful for all the cases where the datasets are not free, for reproducing the code and experimenting at least with that (and not the actual results).
